pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'deploy_to_stagingEnv'

            }
            
        }
    }
}